### ISSUE TITLE
Failed to compile libz-ng-sys v1.1.8 on armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/libz-sys#107] opened 2022-10-08 01:03 UTC
Running cmd

```bash
cross build --target armv7-unknown-linux-gnueabihf --profile release --no-default-features --features zlib-ng,static,rustls,trust-dns,fancy-no-backtrace,log_release_max_level_debug -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
```

on cargo-binstall v0.15.0 failed with error:

```
  /usr/lib/gcc-cross/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
   #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
```

From [CI failure](https://github.com/cargo-bins/cargo-binstall/actions/runs/3205368344/jobs/5238021124).

and

```
  In file included from /cargo/registry/src/index.crates.io-e139d0d48fed7772/libz-ng-sys-1.1.8/src/zlib-ng/compare256.c:7:0:
  /cargo/registry/src/index.crates.io-e139d0d48fed7772/libz-ng-sys-1.1.8/src/zlib-ng/fallback_builtins.h:102:15: error: unknown type name 'uint16x8x4_t'
   static inline uint16x8x4_t vld1q_u16_x4(uint16_t *a) {
```

According to [this comment](https://github.com/cross-rs/cross/issues/1066#issuecomment-1272182940):

> This isn't a cross bug: it's an issue with the library you're trying to use: ARMv7HF defaults to using VFPv3, not NEON, and refuses to compile NEON intrinsics unless you basically force it to. You'd have to add -C target-feature=+neon to RUSTFLAGS, and even then I doubt it would work. If you want an ARMv7 hard-float target that supports NEON by default, use thumbv7neon-unknown-linux-gnueabihf. FYI: your library is also asking you to use -mfloat-abi=softfp which is definitely wrong here: it would have to be -mfloat-abi=hard.
> 
> There's something wrong with the libraries you are using, not with the toolchain itself.

libz-ng should not use NEON intrinsics on armv7hf and it should also use hard float-abi.

**Comment by JohnTitor** [comment] 2022-10-27 22:28
Seems duplicate of #108, closing.

**Closed by JohnTitor** 2022-10-27 22:28 UTC
